#----------------------------------------------------------------------------
#       Make Workspace
#
# 
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# ../../cs36300/MPC/mwc.pl -type make
#
#----------------------------------------------------------------------------


all: HSS

depend: HSS-depend

clean generated realclean check-syntax $(CUSTOM_TARGETS):
	@$(MAKE) -f Makefile.HSS $(@)

.PHONY: HSS
HSS:
	@$(MAKE) -f Makefile.HSS all

.PHONY: HSS-depend
HSS-depend:
	@$(MAKE) -f Makefile.HSS depend

project_name_list:
	@echo HSS
